### PR TITLE
Removed unecessary -ti when starting the web container

### PR DESCRIPTION
**Pull request by luebken**
-ti is unnecessary and might cause questions.

### CODE REVIEW

**Comment by luebken** [comment]
@marians RFR

**Comment by marians** [comment]
What's the intended behaviour of `make docker-run`? Should there be log output visible or should it run in the background? If the latter, `-d` would be required instead, right?

**Comment by luebken** [comment]
no behaviour change in this PR. `make docker-run` should run in the foreground. the log output should be visible right away.

**Comment by marians** [comment]
OK, fine with me :)

**Pull request merged**
