### PR TITLE
Update Makefile to reflect new app name.

### PR DESCRIPTION
**Pull request by shindakun**
Updated Makefile to match appname from swarm.json.

### CODE REVIEW

**Comment by marians** [comment]
Thanks for the fix, @shindakun !

**Comment by shindakun** [comment]
@marians There was one other repo that had a similar problem, can't remember which one off hand but if I have a chance later I'll see if I can track it down.

**Comment by marians** [comment]
Thanks, I found some more.

**Comment by shindakun** [comment]
:+1:

**Pull request merged**
